### ISSUE TITLE
Watchdog & Pm2

### ISSUE THREAD

**Issue by ar84** [MichMich/MMM-WatchDog#2]
Hello everybody. How do I get the mirror restarted after a crash.

The problem is the watchdog MM closes without which I see an error via PM2 logs and afterwards the mirror is not restarted. Must restart it by hand via SSH and the pm2 start command

best regards

**Comment by flyingchipmunk** [comment]
Late to the party, but I just submitted pull request #3 that addresses this. I was in the same boat.
